### ISSUE TITLE
lambda-calculus.js incorrect / contradictory

### ISSUE THREAD

**Issue by jasoncarr0** [MaiaVictor/abstract-algorithm#18]
R. Statman, The typed lambda-calculus is not elementary recursive, Theoretical Computer Science 9 (1979) 73–81.

Specifically, this would be able to evaluate a term to head normal form and determine whether it was 0.

**Comment by jasoncarr0** [comment]
Specifically, this would be able to evaluate a term to head normal form and determine whether it was 0.

**Comment by jasoncarr0** [comment]
Or even more simply, this could loop forever, but all typeable terms for the evaluator are terminating (since they can be simply typed).

**Comment by jasoncarr0** [comment]
An example failing term (not EAL typeable). I ran this at hash 4f0660853501959754e9474e03d27792167343ff (i.e. from the old repo)

(λn.(n λy.(n λz.y)) λx.(x (x y))) (λa.a)
var input = `App
    (Lam
        (App
            (App Var
                (Lam (App (Box Var) (Lam (Box Var)))))
            (Lam (App Var (App Var (Lam Var Var))))))
    (Lam Var Var)`

Evaluating with javascript gives the correct result. Evaluating it with this loops infinitely.
``
Evaluating it with JavaScript:
Result: a.b.b
/home/jason/repos/abstract-algorithm/examples/lambda-calculus.js:79
  var go = ter => ter(bod => "λ" + go(bod))(fun => arg => "(" + go(fun) + " " + go(arg) + ")")(vaa => 1 + go(vaa))(0);
           ^

RangeError: Maximum call stack size exceeded
    at go (/home/jason/repos/abstract-algorithm/examples/lambda-calculus.js:79:12)
    at bod (/home/jason/repos/abstract-algorithm/examples/lambda-calculus.js:79:36)
    at go (/home/jason/repos/abstract-algorithm/examples/lambda-calculus.js:79:19)
    at bod (/home/jason/repos/abstract-algorithm/examples/lambda-calculus.js:79:36)
    at go (/home/jason/repos/abstract-algorithm/examples/lambda-calculus.js:79:19)
    at bod (/home/jason/repos/abstract-algorithm/examples/lambda-calculus.js:79:36)
    at go (/home/jason/repos/abstract-algorithm/examples/lambda-calculus.js:79:19)
    at bod (/home/jason/repos/abstract-algorithm/examples/lambda-calculus.js:79:36)
    at go (/home/jason/repos/abstract-algorithm/examples/lambda-calculus.js:79:19)
    at bod (/home/jason/repos/abstract-algorithm/examples/lambda-calculus.js:79:36)
``
